# Generated by Django 3.0.5 on 2020-10-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=245)),
                ('expiry_date_time', models.CharField(max_length=245)),
            ],
        ),
    ]
